var annotated_dup =
[
    [ "agg", "structagg.html", "structagg" ],
    [ "agg_typed", "structagg__typed.html", "structagg__typed" ],
    [ "canopen_od_init", "structcanopen__od__init.html", "structcanopen__od__init" ],
    [ "cmd", "structcmd.html", "structcmd" ],
    [ "dashboard_mode_info", "structdashboard__mode__info.html", "structdashboard__mode__info" ],
    [ "err", "structerr.html", "structerr" ],
    [ "err_callback", "structerr__callback.html", "structerr__callback" ],
    [ "err_filter", "structerr__filter.html", "structerr__filter" ],
    [ "msg_3d_data", "unionmsg__3d__data.html", "unionmsg__3d__data" ],
    [ "msg_4wheel_data", "unionmsg__4wheel__data.html", "unionmsg__4wheel__data" ],
    [ "msg_4wheel_flags", "unionmsg__4wheel__flags.html", "unionmsg__4wheel__flags" ],
    [ "msg_chan_data", "structmsg__chan__data.html", "structmsg__chan__data" ],
    [ "msg_ctrl_torque", "structmsg__ctrl__torque.html", "structmsg__ctrl__torque" ],
    [ "msg_ctrl_word", "structmsg__ctrl__word.html", "structmsg__ctrl__word" ],
    [ "msg_header", "structmsg__header.html", "structmsg__header" ],
    [ "msg_logging", "structmsg__logging.html", "structmsg__logging" ],
    [ "msg_sensor_cockpit", "structmsg__sensor__cockpit.html", "structmsg__sensor__cockpit" ],
    [ "msg_sensor_gps", "structmsg__sensor__gps.html", "structmsg__sensor__gps" ],
    [ "msg_sensor_imu", "structmsg__sensor__imu.html", "structmsg__sensor__imu" ],
    [ "msg_sensor_pow", "structmsg__sensor__pow.html", "structmsg__sensor__pow" ],
    [ "msg_sensor_wheel", "structmsg__sensor__wheel.html", "structmsg__sensor__wheel" ],
    [ "msg_states", "structmsg__states.html", "structmsg__states" ],
    [ "msg_ts_acc", "structmsg__ts__acc.html", "structmsg__ts__acc" ],
    [ "msg_ts_emcy_stop", "structmsg__ts__emcy__stop.html", "structmsg__ts__emcy__stop" ],
    [ "msg_ts_inv", "structmsg__ts__inv.html", "structmsg__ts__inv" ],
    [ "sensor_tol", "structsensor__tol.html", "structsensor__tol" ],
    [ "states_callback", "structstates__callback.html", "structstates__callback" ],
    [ "states_trans_cmd_info", "structstates__trans__cmd__info.html", "structstates__trans__cmd__info" ],
    [ "sys_shutdown_callback", "structsys__shutdown__callback.html", "structsys__shutdown__callback" ],
    [ "tm_data", "structtm__data.html", "structtm__data" ],
    [ "tm_group", "structtm__group.html", "structtm__group" ],
    [ "tm_group_data", "structtm__group__data.html", "structtm__group__data" ],
    [ "work_ctx", "structwork__ctx.html", "structwork__ctx" ],
    [ "work_ctx_buf", "structwork__ctx__buf.html", "structwork__ctx__buf" ]
];